version: '3.8'

services:
  cybercart-db:
    image: postgres:latest
    container_name: cybercart-db
    environment:
      POSTGRES_DB: cybercart
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

