version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: untitled_postgres_container
    environment:
      POSTGRES_DB: untitled
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

